# Generated by Django 3.0.5 on 2020-04-20 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bpsapp', '0002_auto_20200418_0243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationreview',
            old_name='visitor',
            new_name='commenter',
        ),
    ]
