# Generated by Django 3.0.5 on 2020-04-22 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bpsapp', '0004_auto_20200420_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationreview',
            name='root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bpsapp.LocationReview'),
        ),
    ]
