# Generated by Django 3.0.5 on 2020-08-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpsapp', '0007_auto_20200425_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationreview',
            name='rating',
            field=models.IntegerField(choices=[(5, 5), (4, 4), (3, 3), (2, 2), (1, 1)]),
        ),
    ]
